plugins {
    id 'java'
}

group = 'link.e4mc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

compileJava {
    sourceCompatibility = 17
    targetCompatibility = 17
}

dependencies {
    implementation("io.netty:netty-all:4.1.130.Final")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}