plugins {
    id 'java'
    id 'maven-publish'
}

group = 'link.e4mc'
version = '0.1.1'

repositories {
    mavenCentral()
}

compileJava {
    sourceCompatibility = 17
    targetCompatibility = 17
}

dependencies {
    implementation("io.netty:netty-all:4.1.130.Final")
    implementation("dev.dirs:directories:26")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

if (hasProperty("skyevenToken")) {
    publishing {
        publications {
            maven(MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "https://sg.storage.bunnycdn.com/skyeven"
                credentials(HttpHeaderCredentials) {
                    name = "AccessKey"
                    value = property("skyevenToken")
                }
                authentication {
                    header(HttpHeaderAuthentication)
                }
            }
        }
    }
}