[package]
name = "iroh-java"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["macros"]

[lib]
crate-type = ["cdylib"]
name = "iroh_java"

[dependencies]
anyhow = "1.0.100"
crossbeam-channel = "0.5.15"
iroh = "1.0.3"
iroh-java-proc-macros = { path = "macros" }
iroh-tickets = "1.0.0"
jni = "0.21.1"
log = "0.4.29"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
zerocopy = "0.8.31"